// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package toolsmock

import (
	"context"

	"github.com/slok/sloth/internal/http/backend/app"
	mock "github.com/stretchr/testify/mock"
)

// NewSLOGetter creates a new instance of SLOGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSLOGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SLOGetter {
	mock := &SLOGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SLOGetter is an autogenerated mock type for the SLOGetter type
type SLOGetter struct {
	mock.Mock
}

type SLOGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *SLOGetter) EXPECT() *SLOGetter_Expecter {
	return &SLOGetter_Expecter{mock: &_m.Mock}
}

// GetSLO provides a mock function for the type SLOGetter
func (_mock *SLOGetter) GetSLO(ctx context.Context, req app.GetSLORequest) (*app.GetSLOResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetSLO")
	}

	var r0 *app.GetSLOResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.GetSLORequest) (*app.GetSLOResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.GetSLORequest) *app.GetSLOResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.GetSLOResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.GetSLORequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SLOGetter_GetSLO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSLO'
type SLOGetter_GetSLO_Call struct {
	*mock.Call
}

// GetSLO is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.GetSLORequest
func (_e *SLOGetter_Expecter) GetSLO(ctx interface{}, req interface{}) *SLOGetter_GetSLO_Call {
	return &SLOGetter_GetSLO_Call{Call: _e.mock.On("GetSLO", ctx, req)}
}

func (_c *SLOGetter_GetSLO_Call) Run(run func(ctx context.Context, req app.GetSLORequest)) *SLOGetter_GetSLO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.GetSLORequest
		if args[1] != nil {
			arg1 = args[1].(app.GetSLORequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SLOGetter_GetSLO_Call) Return(getSLOResponse *app.GetSLOResponse, err error) *SLOGetter_GetSLO_Call {
	_c.Call.Return(getSLOResponse, err)
	return _c
}

func (_c *SLOGetter_GetSLO_Call) RunAndReturn(run func(ctx context.Context, req app.GetSLORequest) (*app.GetSLOResponse, error)) *SLOGetter_GetSLO_Call {
	_c.Call.Return(run)
	return _c
}

// NewBurnedBudgetRangeLister creates a new instance of BurnedBudgetRangeLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBurnedBudgetRangeLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *BurnedBudgetRangeLister {
	mock := &BurnedBudgetRangeLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BurnedBudgetRangeLister is an autogenerated mock type for the BurnedBudgetRangeLister type
type BurnedBudgetRangeLister struct {
	mock.Mock
}

type BurnedBudgetRangeLister_Expecter struct {
	mock *mock.Mock
}

func (_m *BurnedBudgetRangeLister) EXPECT() *BurnedBudgetRangeLister_Expecter {
	return &BurnedBudgetRangeLister_Expecter{mock: &_m.Mock}
}

// ListBurnedBudgetRange provides a mock function for the type BurnedBudgetRangeLister
func (_mock *BurnedBudgetRangeLister) ListBurnedBudgetRange(ctx context.Context, req app.ListBurnedBudgetRangeRequest) (*app.ListBurnedBudgetRangeResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListBurnedBudgetRange")
	}

	var r0 *app.ListBurnedBudgetRangeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListBurnedBudgetRangeRequest) (*app.ListBurnedBudgetRangeResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListBurnedBudgetRangeRequest) *app.ListBurnedBudgetRangeResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.ListBurnedBudgetRangeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.ListBurnedBudgetRangeRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BurnedBudgetRangeLister_ListBurnedBudgetRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBurnedBudgetRange'
type BurnedBudgetRangeLister_ListBurnedBudgetRange_Call struct {
	*mock.Call
}

// ListBurnedBudgetRange is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.ListBurnedBudgetRangeRequest
func (_e *BurnedBudgetRangeLister_Expecter) ListBurnedBudgetRange(ctx interface{}, req interface{}) *BurnedBudgetRangeLister_ListBurnedBudgetRange_Call {
	return &BurnedBudgetRangeLister_ListBurnedBudgetRange_Call{Call: _e.mock.On("ListBurnedBudgetRange", ctx, req)}
}

func (_c *BurnedBudgetRangeLister_ListBurnedBudgetRange_Call) Run(run func(ctx context.Context, req app.ListBurnedBudgetRangeRequest)) *BurnedBudgetRangeLister_ListBurnedBudgetRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ListBurnedBudgetRangeRequest
		if args[1] != nil {
			arg1 = args[1].(app.ListBurnedBudgetRangeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BurnedBudgetRangeLister_ListBurnedBudgetRange_Call) Return(listBurnedBudgetRangeResponse *app.ListBurnedBudgetRangeResponse, err error) *BurnedBudgetRangeLister_ListBurnedBudgetRange_Call {
	_c.Call.Return(listBurnedBudgetRangeResponse, err)
	return _c
}

func (_c *BurnedBudgetRangeLister_ListBurnedBudgetRange_Call) RunAndReturn(run func(ctx context.Context, req app.ListBurnedBudgetRangeRequest) (*app.ListBurnedBudgetRangeResponse, error)) *BurnedBudgetRangeLister_ListBurnedBudgetRange_Call {
	_c.Call.Return(run)
	return _c
}

// NewSLIAvailabilityRangeLister creates a new instance of SLIAvailabilityRangeLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSLIAvailabilityRangeLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *SLIAvailabilityRangeLister {
	mock := &SLIAvailabilityRangeLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SLIAvailabilityRangeLister is an autogenerated mock type for the SLIAvailabilityRangeLister type
type SLIAvailabilityRangeLister struct {
	mock.Mock
}

type SLIAvailabilityRangeLister_Expecter struct {
	mock *mock.Mock
}

func (_m *SLIAvailabilityRangeLister) EXPECT() *SLIAvailabilityRangeLister_Expecter {
	return &SLIAvailabilityRangeLister_Expecter{mock: &_m.Mock}
}

// ListSLIAvailabilityRange provides a mock function for the type SLIAvailabilityRangeLister
func (_mock *SLIAvailabilityRangeLister) ListSLIAvailabilityRange(ctx context.Context, req app.ListSLIAvailabilityRangeRequest) (*app.ListSLIAvailabilityRangeResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListSLIAvailabilityRange")
	}

	var r0 *app.ListSLIAvailabilityRangeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListSLIAvailabilityRangeRequest) (*app.ListSLIAvailabilityRangeResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListSLIAvailabilityRangeRequest) *app.ListSLIAvailabilityRangeResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.ListSLIAvailabilityRangeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.ListSLIAvailabilityRangeRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SLIAvailabilityRangeLister_ListSLIAvailabilityRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSLIAvailabilityRange'
type SLIAvailabilityRangeLister_ListSLIAvailabilityRange_Call struct {
	*mock.Call
}

// ListSLIAvailabilityRange is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.ListSLIAvailabilityRangeRequest
func (_e *SLIAvailabilityRangeLister_Expecter) ListSLIAvailabilityRange(ctx interface{}, req interface{}) *SLIAvailabilityRangeLister_ListSLIAvailabilityRange_Call {
	return &SLIAvailabilityRangeLister_ListSLIAvailabilityRange_Call{Call: _e.mock.On("ListSLIAvailabilityRange", ctx, req)}
}

func (_c *SLIAvailabilityRangeLister_ListSLIAvailabilityRange_Call) Run(run func(ctx context.Context, req app.ListSLIAvailabilityRangeRequest)) *SLIAvailabilityRangeLister_ListSLIAvailabilityRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ListSLIAvailabilityRangeRequest
		if args[1] != nil {
			arg1 = args[1].(app.ListSLIAvailabilityRangeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SLIAvailabilityRangeLister_ListSLIAvailabilityRange_Call) Return(listSLIAvailabilityRangeResponse *app.ListSLIAvailabilityRangeResponse, err error) *SLIAvailabilityRangeLister_ListSLIAvailabilityRange_Call {
	_c.Call.Return(listSLIAvailabilityRangeResponse, err)
	return _c
}

func (_c *SLIAvailabilityRangeLister_ListSLIAvailabilityRange_Call) RunAndReturn(run func(ctx context.Context, req app.ListSLIAvailabilityRangeRequest) (*app.ListSLIAvailabilityRangeResponse, error)) *SLIAvailabilityRangeLister_ListSLIAvailabilityRange_Call {
	_c.Call.Return(run)
	return _c
}

// NewServiceLister creates a new instance of ServiceLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceLister {
	mock := &ServiceLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceLister is an autogenerated mock type for the ServiceLister type
type ServiceLister struct {
	mock.Mock
}

type ServiceLister_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceLister) EXPECT() *ServiceLister_Expecter {
	return &ServiceLister_Expecter{mock: &_m.Mock}
}

// ListServices provides a mock function for the type ServiceLister
func (_mock *ServiceLister) ListServices(ctx context.Context, req app.ListServicesRequest) (*app.ListServicesResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListServices")
	}

	var r0 *app.ListServicesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListServicesRequest) (*app.ListServicesResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListServicesRequest) *app.ListServicesResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.ListServicesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.ListServicesRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceLister_ListServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServices'
type ServiceLister_ListServices_Call struct {
	*mock.Call
}

// ListServices is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.ListServicesRequest
func (_e *ServiceLister_Expecter) ListServices(ctx interface{}, req interface{}) *ServiceLister_ListServices_Call {
	return &ServiceLister_ListServices_Call{Call: _e.mock.On("ListServices", ctx, req)}
}

func (_c *ServiceLister_ListServices_Call) Run(run func(ctx context.Context, req app.ListServicesRequest)) *ServiceLister_ListServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ListServicesRequest
		if args[1] != nil {
			arg1 = args[1].(app.ListServicesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceLister_ListServices_Call) Return(listServicesResponse *app.ListServicesResponse, err error) *ServiceLister_ListServices_Call {
	_c.Call.Return(listServicesResponse, err)
	return _c
}

func (_c *ServiceLister_ListServices_Call) RunAndReturn(run func(ctx context.Context, req app.ListServicesRequest) (*app.ListServicesResponse, error)) *ServiceLister_ListServices_Call {
	_c.Call.Return(run)
	return _c
}

// NewSLOLister creates a new instance of SLOLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSLOLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *SLOLister {
	mock := &SLOLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SLOLister is an autogenerated mock type for the SLOLister type
type SLOLister struct {
	mock.Mock
}

type SLOLister_Expecter struct {
	mock *mock.Mock
}

func (_m *SLOLister) EXPECT() *SLOLister_Expecter {
	return &SLOLister_Expecter{mock: &_m.Mock}
}

// ListSLOs provides a mock function for the type SLOLister
func (_mock *SLOLister) ListSLOs(ctx context.Context, req app.ListSLOsRequest) (*app.ListSLOsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListSLOs")
	}

	var r0 *app.ListSLOsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListSLOsRequest) (*app.ListSLOsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.ListSLOsRequest) *app.ListSLOsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.ListSLOsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.ListSLOsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SLOLister_ListSLOs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSLOs'
type SLOLister_ListSLOs_Call struct {
	*mock.Call
}

// ListSLOs is a helper method to define mock.On call
//   - ctx context.Context
//   - req app.ListSLOsRequest
func (_e *SLOLister_Expecter) ListSLOs(ctx interface{}, req interface{}) *SLOLister_ListSLOs_Call {
	return &SLOLister_ListSLOs_Call{Call: _e.mock.On("ListSLOs", ctx, req)}
}

func (_c *SLOLister_ListSLOs_Call) Run(run func(ctx context.Context, req app.ListSLOsRequest)) *SLOLister_ListSLOs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.ListSLOsRequest
		if args[1] != nil {
			arg1 = args[1].(app.ListSLOsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SLOLister_ListSLOs_Call) Return(listSLOsResponse *app.ListSLOsResponse, err error) *SLOLister_ListSLOs_Call {
	_c.Call.Return(listSLOsResponse, err)
	return _c
}

func (_c *SLOLister_ListSLOs_Call) RunAndReturn(run func(ctx context.Context, req app.ListSLOsRequest) (*app.ListSLOsResponse, error)) *SLOLister_ListSLOs_Call {
	_c.Call.Return(run)
	return _c
}
